src/Entity/Advert.php
<?php

namespace App\Entity;

use App\Repository\AdvertRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AdvertRepository::class)
 */
class Advert
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $brand_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getBrandId(): ?int
    {
        return $this->brand_id;
    }

    public function setBrandId(int $brand_id): self
    {
        $this->brand_id = $brand_id;

        return $this;
    }
}

src/Form/AdvertType.php
<?php

namespace App\Form;

use App\Entity\Advert;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdvertType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('brand_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Advert::class,
        ]);
    }
}

src/Controller/AdvertController.php
<?php

namespace App\Controller;

use App\Entity\Advert;
use App\Form\AdvertType;
use App\Repository\AdvertRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/advert")
 */
class AdvertController extends AbstractController
{
    /**
     * @Route("/", name="advert_index", methods={"GET"})
     */
    public function index(AdvertRepository $advertRepository): Response
    {
        return $this->render('advert/index.html.twig', [
            'adverts' => $advertRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="advert_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $advert = new Advert();
        $form = $this->createForm(AdvertType::class, $advert);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($advert);
            $entityManager->flush();

            return $this->redirectToRoute('advert_index');
        }

        return $this->render('advert/new.html.twig', [
            'advert' => $advert,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="advert_show", methods={"GET"})
     */
    public function show(Advert $advert): Response
    {
        return $this->render('advert/show.html.twig', [
            'advert' => $advert,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="advert_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Advert $advert): Response
    {
        $form = $this->createForm(AdvertType::class, $advert);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('advert_index');
        }

        return $this->render('advert/edit.html.twig', [
            'advert' => $advert,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="advert_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Advert $advert): Response
    {
        if ($this->isCsrfTokenValid('delete'.$advert->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($advert);
            $entityManager->flush();
        }

        return $this->redirectToRoute('advert_index');
    }
}

templates/advert/_delete_form.html.twig
<form method="post" action="{{ path('advert_delete', {'id': advert.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ advert.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/advert/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/advert/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer Annonces{% endblock %}

{% block body %}
    <h1>Editer Annonces</h1>

    {{ include('advert/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('advert_index') }}">Retour à la liste</a>

    {{ include('advert/_delete_form.html.twig') }}
{% endblock %}

templates/advert/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Toutes les annonces{% endblock %}

{% block body %}
    <h1>Toutes les annonces</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Référence</th>
                <th>Nom</th>
                <th>Marque</th>
                <th>Réserver</th>
            </tr>
        </thead>
        <tbody>
        {% for advert in adverts %}
            <tr>
                <td>{{ advert.id }}</td>
                <td>{{ advert.name }}</td>
                <td>{{ advert.brandId }}</td>
                <td>
                    <a href="{{ path('advert_show', {'id': advert.id}) }}">show</a>
                    <a href="{{ path('advert_edit', {'id': advert.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">Aucun enregistrement trouvés</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('advert_new') }}">Créer nouveau</a>
{% endblock %}

templates/advert/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle annonce{% endblock %}

{% block body %}
    <h1>Créer une nouvelle annonce</h1>

    {{ include('advert/_form.html.twig') }}

    <a href="{{ path('advert_index') }}">Retour à la liste</a>
{% endblock %}

templates/advert/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annonce{% endblock %}

{% block body %}
    <h1>Annonce</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ advert.id }}</td>
            </tr>
            <tr>
                <th>Non</th>
                <td>{{ advert.name }}</td>
            </tr>
            <tr>
                <th>Marque</th>
                <td>{{ advert.brandId }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('advert_index') }}">Retour à la liste</a>

    <a href="{{ path('user_show', {'id': advert.id}) }}">Réserver</a>

    {{ include('advert/_delete_form.html.twig') }}
{% endblock %}